### ISSUE TITLE
UIの全体的な修正

### ISSUE THREAD

**Issue by yumaueno** [taketomsho/tracky#27]

**Comment by yumaueno** [comment]
- カラムの幅
- ボタンの大きさ・トンマナ
- キーワード・ドメイン登録時のフォーム
- スコア算出結果画面のトンマナ
- トップ画面のPCデモ画面の白背景

**Comment by taketomsho** [comment]
redisの結果保持時間変更：
https://python-rq.org/docs/results/#dealing-with-results
`q.enqueue(scraper.get_result, result_ttl=86400)`
