### ISSUE TITLE
有料プラン実装

### ISSUE THREAD

**Issue by yumaueno** [taketomsho/tracky#28]

**Comment by yumaueno** [comment]
DjangoにStripeでのサブスク決済導入している事例
- https://zenn.dev/var/articles/65785548e340fc

**Comment by taketomsho** [comment]
https://stripe.com/docs/billing

**Comment by yumaueno** [comment]
- https://di-acc2.com/programming/python/19648/
- https://qiita.com/k_ken/items/444aaae741ea61abb639

**Comment by yumaueno** [comment]
決済をStripeで通せるようになった！

以下 to do
- 決済周りのUI修正
- 会員のレベルを定義して実装
-- 無料会員
-- 有料会員

**Comment by yumaueno** [comment]
決済後に顧客データをDBに突っ込む処理ができない

**Comment by yumaueno** [comment]
- 通常の会員登録と組み合わせて、会員レベルによって機能制御できるようにする

**Comment by yumaueno** [comment]
9月27日MTG
- 無料会員登録→スコア登録だけできる、かつキーワードとURLは一部だけ
- 有料会員登録→キーワードとURLの上限突破

**Comment by yumaueno** [comment]
おい、DB登録ができなくなってるぞーい。わけわからんぞい

**Comment by yumaueno** [comment]
■to do

- [ ] 解約ができるようにする
- [ ] メンバーページに行って自分の契約済みのプランは表示されないようにする
- [ ] 無料プランと有料プランのURLとキーワードの登録上限を作る

**Comment by yumaueno** [comment]
https://zenn.dev/fujiikayo/articles/12332edfa9e90e

**Comment by yumaueno** [comment]
- 仕様について簡単にまとめておく！
