### ISSUE TITLE
ドメイン・キーワードリストの修正

### ISSUE THREAD

**Issue by yumaueno** [taketomsho/tracky#43]

**Comment by taketomsho** [comment]
- カードの幅を狭くして横並びで表示できるようにする
- サイドバーのボタンに追加、画面内は削除

**Comment by taketomsho** [comment]
- segmentに注意（サイドバーボタンのアクティブ、非アクティブ制御）
- ダッシュボードのボタンが消えている

**Comment by taketomsho** [comment]
プルリクに"fixes #<issue番号>"を記入すること！

**Comment by yumaueno** [comment]
@nakkinao 
これもう1回プルリクエスト送ってほしい！
